#include "stim/diagram/crumble_data.h"

std::string stim_draw_internal::make_crumble_html() {
    std::string result;
    result.append(R"CRUMBLE_PART(<!DOCTYPE html>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(<html lang="en">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(<head>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <meta charset="UTF-8">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <title>Crumble</title>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABgWlDQ1BJQ0MgcHJvZmlsZQAAKJF9kTlIA0EUhj+j4kHEwhQiFluolQFREUuNgggRQlTwKtzdnJBdw27ExlKwDVh4NF6FjbW2FraCIHiAWFpZKdpIWN8kgQQxDgzz8c/8j/f+Ad9RxrTchgGw7JwTnQppC4tLWtMrrfiAAC266WbHI5EwNdfXPXXqvAuqWrXf/bnaYnHXhDpNeMzMOjnhVeGRjVxW8Z7qwkzpMeFz4X5HGhR+VLpR4jfFySKrpgk4c9EJ4YCwlqxio4rNlGMJDwv3xCxb6vsWShxTvKnYyqyb5T7VhP64PT+rdNndTDHNDBE0DNZJkyFHUE5bFJeo3Idq+LuK/oi4DHGlMcUxyRoWetGP+oPf2bqJocFSJX8IGl8876MXmnagkPe872PPK5xA/TNc2RX/2hGMfoqer2g9h9C+BRfXFc3Yhctt6HzK6o5elOpl+xIJeD+Tb1qEjltoXS7lVr7n9AHmJKvwDewfQF9Saq/UmLu5Ord/35Tz+wHVp3JoxsjWZAAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+YKAhYQLxXIct8AAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAx0lEQVRYw+2XwQ7EIAhEB+N/E76cnkgIa6OuWTFxvTWxdRgKDwmAYu+i+KDKPP62CJjHNYsQ7Psk8iGk7AxdmeGC1e0CvBBbKQK8ljQB5kK2AxcLsJLMdoBKZvQAULMOtk5IR7Dg294+yw4RymUBs3qQ5bHAO34vC8yFPwvSBFhJ3skC35Bq1sHHsKDGKfUX94J46HllGDjd5XnI5WjOXwXQSg5X95eXaaU3zXSjG3XJ79LW1ak1RsX9/qdsldqsPTppo66k6QGRuElWZ7d4CQAAAABJRU)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(5ErkJggg==">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(</head>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(<body style="margin: 0">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    This is a <strong>prototype</strong> of crumble, an interactive editor for 2d stabilizer circuit.<br>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    It is still in development. It is not stable or polished.<br>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnShowHideImportExport">Show Import/Export</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="clear">Clear</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnClearMarkers">Clear Pauli Frames</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnUndo">Undo (ctrl+Z)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnRedo">Redo (ctrl+Y)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnPrevLayer">Prev Layer (q)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnNextLayer">Next Layer (e)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnRotate45">Rotate 45 Clockwise ↻ (t)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <button id="btnRotate45Counter">Rotate 45 Mathwise ↺ (shift+t)</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <textarea id="txtDefaultCircuit" style="display: none">[[[DEFAULT_CIRCUIT_CONTENT_LITERAL]]]</textarea>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <canvas id="toolbox" style="width: 500px; height: 120px; border: 1px solid black; margin: 0; padding: 0;">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    </canvas>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <div id="divImportExport" style="display: none">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(        <div>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(            <textarea id="txtStimCircuit" style="width: 95vw; height: 300px; background-color: #FFFFB0">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(            </textarea>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(        </div>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(        <button id="btnExport" style="background-color: red">↑ Export to Stim Circuit ↑</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(        <button id="btnImport" style="background-color: red">↓ Import from Stim Circuit ↓</button>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    </div>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    <canvas id="cvn" style="width: 95vw; height: 80vh; border: 1px solid black; margin: 0; padding: 0;" tabindex="0">
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    </canvas>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(</body>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(</html>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(<script>
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(class i{constructor(t,r,e,i,o,a,n,s=void 0){this.name=t,this.t=r,this.i=i,this.o=e,this.l=o,this.h=a,this.v=n,this.u=s}X(t){return new i(this.name,this.t,this.o,this.i,this.l,this.h,this.v,t)}}function E(r){var e=[];for(let t=0;t<r.length;t++){var i="I".repeat(t),o="I".repeat(r.length-t-1);"X"!==r[t]&&"Y"!==r[t]||e.push(i+"X"+o),"Z"!==r[t]&&"Y"!==r[t]||e.push(i+"Z"+o)}return e}class b{constructor(t,r,e){if(!(t instanceof i))throw new Error("!(gate instanceof Gate)");if(!(r instanceof Float32Array))throw new Error("!(args instanceof Float32Array)");if(!(e instanceof Uint32Array))throw new Error("!(targets instanceof Uint32Array)");this.Z=t,this.Y=r,this.R=e}M(r){let e=this.Z.l;if(void 0===e)return r;if(r.length!==this.Z.t)throw new Error("before.length !== this.gate.num_qubits");if(e.has(r))return e.get(r);let t=E(r);var i,o=[0,0];for(i of t=t.map(t=>e.get(t)))for(let t=0;t<r.length;t++)"X"===i[t]&&(o[t]^=1),"Y"===i[t]&&(o[t]^=3),"Z"===i[t]&&(o[t]^=2);let a="";for(let t=0;t<r.length;t++)a+="IXZY"[o[t]];return )CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(a}I(t,r){r.save();try{this.Z.v(this,t,r)}finally{r.restore()}}}const d=50,nt=10;function a(t,r,e){void 0!==r&&void 0!==e&&(t.strokeStyle="black",t.fillStyle="white",t.beginPath(),t.arc(r,e,nt,0,2*Math.PI),t.fill(),t.stroke(),t.beginPath(),t.moveTo(r,e-nt),t.lineTo(r,e+nt),t.stroke(),t.beginPath(),t.moveTo(r-nt,e),t.lineTo(r+nt,e),t.stroke())}function n(t,r,e){void 0!==r&&void 0!==e&&(t.strokeStyle="black",t.fillStyle="#AAA",t.beginPath(),t.moveTo(r,e+nt),t.lineTo(r+nt,e-nt),t.lineTo(r-nt,e-nt),t.lineTo(r,e+nt),t.stroke(),t.fill())}function s(t,r,e){void 0!==r&&void 0!==e&&(t.fillStyle="black",t.beginPath(),t.arc(r,e,nt,0,2*Math.PI),t.fill())}function l(t,r,e){var i;void 0!==r&&void 0!==e&&(t.fillStyle="gray",t.beginPath(),t.arc(r,e,nt,0,2*Math.PI),t.fill(),i=nt/3,t.strokeStyle="black",t.beginPath(),t.moveTo(r-i,e-i),t.lineTo(r+i,e+i),t.stroke(),t.moveTo(r-i,e+i),t.lineTo(r+i,e-i),t.stroke())}function C(t,r,e){var i;void 0!==r&&void 0!==e&&(i=nt/3,t.strokeStyle="black",t.beginPath(),t.moveTo(r-i,e-i),t.lineTo()CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(r+i,e+i),t.stroke(),t.moveTo(r-i,e+i),t.lineTo(r+i,e-i),t.stroke())}function _(t,r,e){var i;void 0!==r&&void 0!==e&&(i=1.1*nt,t.strokeRect(r-i,e-i,2*i,2*i))}function st(t,r,e,i,o){var a,n,s,l,h;void 0===r||void 0===e||void 0===i||void 0===o?(_(t,r,e),_(t,i,o)):i<r||i===r&&o<e?st(t,i,o,r,e):(n=i-r,l=s=(a=o-e)/(a=Math.sqrt(n*n+a*a))*14,h=-(n=n/a*14),t.beginPath(),t.moveTo(r,e),a<1.1*d?t.lineTo(i,o):t.bezierCurveTo(r+n+l,e+s+h,i-n+l,o-s+h,i,o),t.stroke())}function h(t,r,e,i,o){t.lineWidth=2,t.strokeStyle="black",st(t,r,e,i,o),t.lineWidth=1}function B(e,i){if(e.beginPath(),0!==i.length){var r=i.length;if(1===r){var[[o,a]]=i;e.arc(o,a,1.7*nt,0,2*Math.PI)}else if(2===r){var[[o,a],[n,s]]=i,l=n-o,h=s-a,f=(n+o)/2,c=(s+a)/2;let t=-h,r=l;var v=t*t+r*r,v=(2500<v&&(v=50/Math.sqrt(v),t*=v,r*=v),f+.2*t-.2*l),d=c+.2*r-.2*h,w=f+.2*t+.2*l,u=c+.2*r+.2*h,X=f-.2*t-.2*l,Z=c-.2*r-.2*h,f=f-.2*t+.2*l,l=c-.2*r+.2*h;e.moveTo(o,a),e.bezierCurveTo(v,d,w,u,n,s),e.bezierCurveTo(f,l,X,Z,o,a)}else{var[c,h]=i[r-1];e.moveTo(c,h);for(let t=0;t<)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(r;t++){var[Y,R]=i[t];e.lineTo(Y,R)}}}}function U(t){let r,e,i,o;return o=0===t?(r=nt,e=nt+5,i=2*nt,5):1===t?(r=-nt,e=nt,i=5,2*nt):2===t?(r=nt,e=-nt,i=2*nt,5):3===t?(r=nt+5,e=nt,i=5,2*nt):(r=Math.cos(t/5)*nt,e=Math.sin(t/5)*nt,i=5),{dx:r,dy:e,m:i,p:o}}function*g(){yield new i("CX",2,!0,!1,new Map([["IX","IX"],["IZ","ZZ"],["XI","XX"],["ZI","ZI"]]),(t,r)=>t.do_cx(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),s(e,i,o),a(e,r,t)}),yield new i("CY",2,!0,!1,new Map([["IX","ZX"],["IZ","ZZ"],["XI","XY"],["ZI","ZI"]]),(t,r)=>t.do_cy(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),s(e,i,o),n(e,r,t)}),yield new i("XCX",2,!0,!1,new Map([["IX","IX"],["IZ","XZ"],["XI","XI"],["ZI","ZX"]]),(t,r)=>t.do_xcx(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),a(e,i,o),a(e,r,t)}),yield new i("XCY",2,!0,!1,new Map([["IX","XX"],["IZ","XZ"],["XI","XI"],["ZI","ZY"]]),(t,r)=>t.do_xcy(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),a(e,i,o),n(e,r,t)}),yield new i("YCY",2,!0,!1,new Map([[)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART("IX","YX"],["IZ","YZ"],["XI","XY"],["ZI","ZY"]]),(t,r)=>t.do_ycy(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),n(e,i,o),n(e,r,t)}),yield new i("CZ",2,!0,!1,new Map([["IX","ZX"],["IZ","IZ"],["XI","XZ"],["ZI","ZI"]]),(t,r)=>t.do_cz(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),s(e,i,o),s(e,r,t)}),yield new i("MR",1,!0,!1,new Map([["X","ERR:I"],["Y","ERR:I"],["Z","I"]]),(t,r)=>t.do_demolition_measure("Z",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MR",r,t)}),yield new i("MRY",1,!0,!1,new Map([["X","ERR:I"],["Y","I"],["Z","ERR:I"]]),(t,r)=>t.do_demolition_measure("Y",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MRY",r,t)}),yield new i("MRX",1,!0,!)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(1,new Map([["X","I"],["Y","ERR:I"],["Z","ERR:I"]]),(t,r)=>t.do_demolition_measure("X",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MRX",r,t)}),yield new i("H",1,!0,!1,new Map([["X","Z"],["Z","X"]]),(t,r)=>t.do_exchange_xz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("H",r,t)}),yield new i("H_XY",1,!0,!1,new Map([["X","Y"],["Z","Z"]]),(t,r)=>t.do_exchange_xy(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("H",r,t-nt/3),e.fillText("XY",r,t+nt/3)}),yield new i("H_YZ",1,!0,!1,new Map([["X","X"],["Z","Y"]]),(t,r)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART()=>t.do_exchange_yz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("H",r,t-nt/3),e.fillText("YZ",r,t+nt/3)}),yield new i("POLYGON",void 0,!1,!0,void 0,()=>{},(t,r,e)=>{var i,o=[];for(i of t.R)o.push(r(i));B(e,o),e.globalAlpha*=t.Y[3],e.fillStyle=`rgb(${255*t.Y[0]},${255*t.Y[1]},${255*t.Y[2]})`,e.strokeStyle=`rgb(${32*t.Y[0]},${32*t.Y[1]},${32*t.Y[2]})`,e.fill(),e.stroke()}),yield new i("MARKX",1,!0,!0,void 0,()=>{},(o,a,n)=>{var[a,s]=a(o.R[0]);if(void 0!==a&&void 0!==s){var{dx:o,dy:l,m:h,p:f}=U(o.Y[0]);let t,r,e,i;i=h===f?(t=a+o,r=s+l,e=t+o+h,r+l+f):(t=a+(o<0?1:-1)*nt,r=s+(l<0?1:-1)*nt,e=t+(h>nt?1:0)*nt*2,r+(f>nt?1:0)*nt*2),n.fillStyle="red",n.beginPath(),n.moveTo(a,s),n.lineTo(t,r),n.lineTo(e,i),n.lineTo(a,s),n.fill()}}),yield new i("MARKY",1,!0,!0,void 0,()=>{},(o,a,n)=>{var[a,s]=a(o.R[0]);if(void 0!==a&&void 0!==s){var{dx:o,dy:l,m:h,p:f}=U)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART((o.Y[0]);let t,r,e,i;i=h===f?(t=a+o,r=s+l,e=t+o+h,r+l+f):(t=a+(o<0?1:-1)*nt,r=s+(l<0?1:-1)*nt,e=t+(h>nt?1:0)*nt*2,r+(f>nt?1:0)*nt*2),n.fillStyle="green",n.beginPath(),n.moveTo(a,s),n.lineTo(t,r),n.lineTo(e,i),n.lineTo(a,s),n.fill()}}),yield new i("MARKZ",1,!0,!0,void 0,()=>{},(o,a,n)=>{var[a,s]=a(o.R[0]);if(void 0!==a&&void 0!==s){var{dx:o,dy:l,m:h,p:f}=U(o.Y[0]);let t,r,e,i;i=h===f?(t=a+o,r=s+l,e=t+o+h,r+l+f):(t=a+(o<0?1:-1)*nt,r=s+(l<0?1:-1)*nt,e=t+(h>nt?1:0)*nt*2,r+(f>nt?1:0)*nt*2),n.fillStyle="blue",n.beginPath(),n.moveTo(a,s),n.lineTo(t,r),n.lineTo(e,i),n.lineTo(a,s),n.fill()}}),yield new i("MARK",1,!1,!0,void 0,()=>{},(t,r,e)=>{var[r,t]=r(t.R[0]);void 0!==r&&void 0!==t&&(e.fillStyle="magenta",e.fillRect(r-nt,t-nt,nt,nt))}),yield new i("MXX",2,!0,!1,new Map([["II","II"],["IX","IX"],["IY","ERR:IY"],["IZ","ERR:IZ"],["XI","XI"],["XX","XX"],["XY","ERR:XY"],["XZ","ERR:XZ"],["YI","ERR:YI"],["YX","ERR:YX"],["YY","YY"],["YZ","YZ"],["ZI","ERR:ZI"],["ZX","ERR:ZX"],["ZY","ZY"],["ZZ","ZZ"]]),(t,r)=>t.do_measure("XX")CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(,r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),e.fillStyle="gray",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MXX",i,o),e.fillText("MXX",r,t)}),yield new i("MYY",2,!0,!1,new Map([["II","II"],["IX","ERR:IX"],["IY","IY"],["IZ","ERR:IZ"],["XI","ERR:XI"],["XX","XX"],["XY","ERR:XY"],["XZ","XZ"],["YI","YI"],["YX","ERR:YX"],["YY","YY"],["YZ","ERR:YZ"],["ZI","ERR:ZI"],["ZX","ZX"],["ZY","ERR:ZY"],["ZZ","ZZ"]]),(t,r)=>t.do_measure("YY",r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),e.fillStyle="gray",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MYY",i,o),e.fillText("MYY",r,t)}),yield new i("MZZ",2,!0,!1,new Map([["II","II"],)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(["IX","ERR:IX"],["IY","ERR:IY"],["IZ","IZ"],["XI","ERR:XI"],["XX","XX"],["XY","XY"],["XZ","ERR:XZ"],["YI","ERR:YI"],["YX","YX"],["YY","YY"],["YZ","ERR:YZ"],["ZI","ZI"],["ZX","ERR:ZX"],["ZY","ERR:ZY"],["ZZ","ZZ"]]),(t,r)=>t.do_measure("ZZ",r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),e.fillStyle="gray",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MZZ",i,o),e.fillText("MZZ",r,t)}),yield new i("I",1,!0,!1,new Map([["X","X"],["Z","Z"]]),()=>{},(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="white",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("I",r,t)}),yield new i("X",1,!0,!1,new Map([["X","X"],["Z","Z"]]),()=>{},(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="white",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeSty)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(le="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("X",r,t)}),yield new i("Y",1,!0,!1,new Map([["X","X"],["Z","Z"]]),()=>{},(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="white",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("Y",r,t)}),yield new i("Z",1,!0,!1,new Map([["X","X"],["Z","Z"]]),()=>{},(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="white",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("Z",r,t)}),yield new i("S",1,!0,!1,new Map([["X","Y"],["Z","Z"]]),(t,r)=>t.do_exchange_xy(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("S",r,t)}),yield new i(")CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(S_DAG",1,!0,!1,new Map([["X","Y"],["Z","Z"]]),(t,r)=>t.do_exchange_xy(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("S†",r,t)}),yield new i("SQRT_X",1,!0,!1,new Map([["X","X"],["Z","Y"]]),(t,r)=>t.do_exchange_yz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√X",r,t)}),yield new i("SQRT_X_DAG",1,!0,!1,new Map([["X","X"],["Z","Y"]]),(t,r)=>t.do_exchange_yz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√X†",r,t)}),yield new i("SQRT_Y",1,!0,!1,new Map([["X","Z"],["Z","X"]]),(t,r)=>t.do_exchange_xz(r),(t,r,e))CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√Y",r,t)}),yield new i("SQRT_Y_DAG",1,!0,!1,new Map([["X","Z"],["Z","X"]]),(t,r)=>t.do_exchange_xz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="yellow",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√Y†",r,t)}),yield new i("R",1,!0,!1,new Map([["X","ERR:I"],["Y","ERR:I"],["Z","ERR:I"]]),(t,r)=>t.do_discard(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("R",r,t)}),yield new i("RX",1,!0,!1,new Map([["X","ERR:I"],["Y","ERR:I"],["Z","ERR:I"]]),(t,r)=>t.do_discard(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("RX",r,t)}),yield new i("RY",1,!0,!1,new Map([["X","ERR:I"],["Y","ERR:I"],["Z","ERR:I"]]),(t,r)=>t.do_discard(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("RY",r,t)}),yield new i("M",1,!0,!1,new Map([["X","ERR:X"],["Y","ERR:Y"],["Z","Z"]]),(t,r)=>t.do_measure("Z",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("M",r,t),e.textAlign="left"}),yield new i("MX",1,!0,!1,new Map([["X","X"],["Y","ERR:Y"],["Z","ERR:Z"]]),(t,r)=>t.do_measure("X",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle=")CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MX",r,t),e.textAlign="left"}),yield new i("MY",1,!0,!1,new Map([["X","ERR:X"],["Y","Y"],["Z","ERR:Z"]]),(t,r)=>t.do_measure("Y",r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="gray",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("MY",r,t),e.textAlign="left"}),yield new i("SQRT_XX",2,!0,!1,new Map([["IX","IX"],["IZ","XY"],["XI","XI"],["ZI","YX"]]),(t,r)=>t.do_sqrt_xx(r),(t,r,e)=>{var i,o,[a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√XX",i,o)}),yield new i("SQRT_XX_DAG",2,!0,!1,new Map([["IX","IX"],["IZ","XY"],["XI","XI"],["ZI","YX"]]),(t,r)=>t.do_sqrt_xx(r),(t,r,e)=>{var i,o,)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART([a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√XX†",i,o)}),yield new i("SQRT_YY",2,!0,!1,new Map([["IX","YZ"],["IZ","YX"],["XI","ZY"],["ZI","XY"]]),(t,r)=>t.do_sqrt_yy(r),(t,r,e)=>{var i,o,[a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√YY",i,o)}),yield new i("SQRT_YY_DAG",2,!0,!1,new Map([["IX","YZ"],["IZ","YX"],["XI","ZY"],["ZI","XY"]]),(t,r)=>t.do_sqrt_yy(r),(t,r,e)=>{var i,o,[a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.t)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(extBaseline="middle",e.fillText("√YY†",i,o)}),yield new i("SQRT_ZZ",2,!0,!1,new Map([["IX","ZY"],["IZ","IZ"],["XI","YZ"],["ZI","ZI"]]),(t,r)=>t.do_sqrt_zz(r),(t,r,e)=>{var i,o,[a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√ZZ",i,o)}),yield new i("SQRT_ZZ_DAG",2,!0,!1,new Map([["IX","ZY"],["IZ","IZ"],["XI","YZ"],["ZI","ZI"]]),(t,r)=>t.do_sqrt_zz(r),(t,r,e)=>{var i,o,[a,n]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,a,n,r,t);for([i,o]of[[a,n],[r,t]])e.fillStyle="yellow",e.fillRect(i-nt,o-nt,2*nt,2*nt),e.strokeStyle="black",e.strokeRect(i-nt,o-nt,2*nt,2*nt),e.fillStyle="black",e.textAlign="center",e.textBaseline="middle",e.fillText("√ZZ†",i,o)}),yield new i("ISWAP",2,!0,!1,new Map([["IX","YZ"],["IZ","ZI"],["XI","ZY"],["ZI","IZ"]]),(t,r)=>t.do_iswap(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),l(e,i,o),l()CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(e,r,t)}),yield new i("ISWAP_DAG",2,!0,!1,new Map([["IX","YZ"],["IZ","ZI"],["XI","ZY"],["ZI","IZ"]]),(t,r)=>t.do_iswap(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),l(e,i,o),l(e,r,t)}),yield new i("SWAP",2,!0,!1,new Map([["IX","XI"],["IZ","ZI"],["XI","IX"],["ZI","IZ"]]),(t,r)=>t.do_swap(r),(t,r,e)=>{var[i,o]=r(t.R[0]),[r,t]=r(t.R[1]);h(e,i,o,r,t),C(e,i,o),C(e,r,t)}),yield new i("C_XYZ",1,!0,!1,new Map([["X","Y"],["Z","X"]]),(t,r)=>t.do_cycle_xyz(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="teal",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.textAlign="center",e.textBaseline="middle",e.fillText("C",r,t-nt/3),e.fillText("XYZ",r,t+nt/3)}),yield new i("C_ZYX",1,!0,!1,new Map([["X","Z"],["Z","Y"]]),(t,r)=>t.do_cycle_zyx(r),(t,r,e)=>{var[r,t]=r(t.R[0]);e.fillStyle="teal",e.fillRect(r-nt,t-nt,2*nt,2*nt),e.fillStyle="black",e.strokeStyle="black",e.strokeRect(r-nt,t-nt,2*nt,2*nt),e.textAlign="center",e.textBaseline="middle",e.fillText("C",r,)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(t-nt/3),e.fillText("ZYX",r,t+nt/3)})}const k=function(){var t,r=new Map;for(t of g())r.set(t.name,t);return r}();class A{constructor(){this.k=new Map,this.A=[]}C(){var t=new A;return t.k=new Map(this.k),t.A=[...this.A],t}empty(){return 0===this.k.size&&0===this.A.length}_(t){var r,e,i=new A;for(r of this.k.values())t(r)&&i.put(r);for(e of this.A)t(e)&&i.A.push(e);return i}g(r){return this._(t=>!t.R.every(t=>!r(t)))}S(e,t){var r,i,o=new Map,a=new Set;for(r of e.keys()){var n=e.get(r),s=this.k.get(r);if(void 0!==s){let r="";for(var l of s.R){a.has(l),a.add(l);let t=e.get(l);void 0===t&&(t="I"),r+=t}var h=s.M(r),f=h.startsWith("ERR:");for(let t=0;t<s.R.length;t++){var c=s.R[t];f?o.set(c,"ERR:"+h[4+t]):o.set(c,h[t])}}else o.set(r,n)}for(i of this.A)if("MARKX"===i.Z.name&&i.Y[0]===t){var v=i.R[0];let t=o.get(v);void 0===t||"I"===t?t="X":"X"===t?t="I":"Y"===t?t="Z":"Z"===t&&(t="Y"),o.set(v,t)}else if("MARKY"===i.Z.name&&i.Y[0]===t){v=i.R[0];let t=o.get(v);void 0===t||"I"===t?t="Y":"X"===t?t="Z":"Y"===t?t="I":"Z"===)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(t&&(t="X"),o.set(v,t)}else if("MARKZ"===i.Z.name&&i.Y[0]===t){var d=i.R[0];let t=o.get(d);void 0===t||"I"===t?t="Z":"X"===t?t="Y":"Y"===t?t="X":"Z"===t&&(t="I"),o.set(d,t)}return o}O(){return 0===this.k.size&&0===this.A.length}T(r){if(this.A=this.A.filter(t=>-1===t.R.indexOf(r)),this.k.has(r)){var t,e=this.k.get(r);for(t of e.R)this.k.delete(t);return e}}K(r,e=void 0){this.A=this.A.filter(t=>void 0!==e&&t.Y[0]!==e||"MARKX"!==t.Z.name&&"MARKY"!==t.Z.name&&"MARKZ"!==t.Z.name||t.R[0]!==r)}put(t,r=!0){if(t.Z.i)"MARKX"!==t.Z.name&&"MARKY"!==t.Z.name&&"MARKZ"!==t.Z.name||this.K(t.R[0],t.Y[0]),this.A.push(t);else{for(var e of t.R)if(this.k.has(e)){if(!r)throw new Error("Collision");this.T(e)}for(var i of t.R)this.k.set(i,t)}}*L(){for(var t of this.k.keys()){var r=this.k.get(t);r.R[0]===t&&(yield r)}yield*this.A}}function Y(t){let r=void 0,e=void 0;for(var[i,o]of t)(void 0===r||i<r||i===r&&o<e)&&(r=i,e=o);return[r,e]}function S(t,r){var e,i=new Map;for(e of t){var o=r(e),a=i.get(o);void 0===a?i.set(o,[e]):a.push(e)}r)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(eturn i}class u{constructor(t,r=[]){if(!(t instanceof Float64Array))throw new Error("!(qubitCoords instanceof Float64Array)");if(!Array.isArray(r))throw new Error("!Array.isArray(layers)");if(!r.every(t=>t instanceof A))throw new Error("!layers.every(e => e instanceof Layer)");this.G=t,this.P=r}static D(t){t=t.replaceAll(";","\n").replaceAll("_"," ").replaceAll("Q(","QUBIT_COORDS(").replaceAll("DT","DETECTOR").replaceAll(" COORDS","_COORDS").replaceAll(" ERROR","_ERROR").replaceAll("C XYZ","C_XYZ").replaceAll("H XY","H_XY").replaceAll("H YZ","H_YZ").replaceAll(" INCLUDE","_INCLUDE").replaceAll("SQRT ","SQRT_").replaceAll(" DAG ","_DAG ").replaceAll("C ZYX","C_ZYX").split("\n");let M=[new A],I=new Map,m=new Set,e=0,p=t=>{for(;!I.has(t);){var r=e+",0";m.has(r)||(m.add(r),I.set(t,[e,0])),e++}},s=(e,i,o,r)=>{M[M.length-1].empty()||M.push(new A);for(let t=0;t<r;t++){for(let r=i;r<o;r++){let t=e[r];var a,n;(t=t.split("#")[0].trim()).toLowerCase().startsWith("repeat ")?(a=parseInt(t.split(" ")[1]),n=((e,t,i)=>{let o)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(=0;for(let r=t;r<i;r++){let t=e[r];if((t=t.split("#")[0].trim()).toLowerCase().startsWith("repeat "))o++;else if("}"===t&&0===--o)return r}throw Error("Repeat block didn't end")})(e,r,o),s(e,r+1,n,a),r=n):(o=>{let a=[],n=[],s="";if(o.indexOf(")")!==-1){let[t,r]=o.split(")");let[e,i]=t.split("(");s=e.trim();a=i.split(",").map(t=>t.trim()).map(parseFloat);n=r.split(" ").map(t=>t.trim()).filter(t=>t!=="")}else{let t=o.split(" ").map(t=>t.trim()).filter(t=>t!=="");if(t.length===0)return;let[r,...e]=t;s=r.trim();a=[];n=e.map(t=>t.trim()).filter(t=>t!=="")}let e=false;if(""!==s){if("XCZ"===s)e=!0,s="CX";else if("CNOT"===s)s="CX";else if("RZ"===s)s="R";else if("MZ"===s)s="M";else if("MRZ"===s)s="MR";else if("ZCX"===s)s="CX";else if("ZCY"===s)s="CY";else if("ZCZ"===s)s="CZ";else if("YCX"===s)e=!0,s="XCY";else if("YCZ"===s)e=!0,s="CY";else{if("TICK"===s)return M.push(new A);if("MPP"===s){M[M.length-1];for(var r of n){let e="M";var l=[],h;for(h of r.split("*"))e+=h[0],l.push(h.substring(1));let i=k.get(e);var f=new Flo)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(at32Array(a),c=M[M.length-1];if(void 0!==i)c.put(new b(i,f,new Uint32Array(l)));else{console.warn("SPLIT MPP INTO INDIVIDUAL MEASUREMENTS");for(let r=0;r<e.length-1;r++){let t="M"+e[r+1];"MZ"===t&&(t="M"),i=k.get(t),c.put(new b(i,f,new Uint32Array(l[r])))}}}return}if("X_ERROR"===s||"Y_ERROR"===s||"Z_ERROR"===s||"DETECTOR"===s||"OBSERVABLE_INCLUDE"===s||"DEPOLARIZE1"===s||"DEPOLARIZE2"===s||"SHIFT_COORDS"===s||"REPEAT"===s||"}"===s)return;if(s.startsWith("QUBIT_COORDS")){var i=a.length<1?0:a[0],v=a.length<2?0:a[1],d;for(d of n){var w=parseInt(d);I.has(w)?console.warn(`Ignoring "${o}" because there's already coordinate data for qubit ${w}.`):m.has(i+","+v)?console.warn(`Ignoring "${o}" because there's already a qubit placed at ${i},${v}.`):(I.set(w,[i,v]),m.add(i+","+v))}return}}let t=!1;for(var u of n){if(u.startsWith("rec[")&&("CX"===s||"CY"===s||"CZ"===s||"ZCX"===s||"ZCY"===s)){t=!0;break}var X=parseInt(u);if("number"!=typeof parseInt(u))throw new Error(o);p(X)}if(t)console.warn("IGNORED",s);else{var Z=k.get)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART((s);if(void 0===Z)throw new Error("Unrecognized gate name in "+o);var Y=new Float32Array(a);let r=M[M.length-1];if(void 0===Z.t)r.put(new b(Z,Y,new Uint32Array(n)));else{if(n.length%Z.t!=0)throw new Error("Incorrect number of targets in line "+o);for(let t=0;t<n.length;t+=Z.t){var R=n.slice(t,t+Z.t),y=(e&&R.reverse(),new Uint32Array(R));try{r.put(new b(Z,Y,y),!1)}catch(t){M.push(new A),(r=M[M.length-1]).put(new b(Z,Y,y),!1)}}}}}})(t)}M[M.length-1].empty()||M.push(new A)}};s(t,0,t.length,1),0<M.length&&M[M.length-1].O()&&M.pop();var r=Math.max(...I.keys(),0)+1,i=new Float64Array(2*r);for(let t=0;t<r;t++){p(t);var[o,a]=I.get(t);i[2*t]=o,i[2*t+1]=a}return new u(i,M)}F(){var t,r=new Set;for(t of this.P)for(var e of t.L())for(var i of e.R)r.add(i);return r}N(){return this.U((t,r)=>[t-r,t+r])}H(){var t,r,e=new Map;for(let t=0;t<this.G.length;t+=2){var i=this.G[t],o=this.G[t+1];e.set(i+","+o,[i,o])}let a=1/0,n=1/0,s=256;for([t,r]of e.values())for(a=Math.min(t,a),n=Math.min(r,n);(t%s!=0||r%s!=0)&&s>1/256;)s/=2;let l;)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(if(s<=1/256)l=1;else{l=1/s;let t=0;for(var[h,f]of e.values()){var c=(h-a+f-n)%(2*s),h=(h-a-f+n)%(2*s);t=t|(0==c?1:2)|(0==h?4:8)}5===t?l/=2:10===t&&(a-=s,l/=2)}let v=-a,d=-n;return(t,r)=>[(t+v)*l,(r+d)*l]}$(){return this.U(this.H())}q(e,i){return this.U((t,r)=>[t+e,r+i])}C(){return this.q(0,0)}U(r){var e=new Float64Array(this.G.length);for(let t=0;t<this.G.length;t+=2){var[i,o]=r(this.G[t],this.G[t+1]);e[t]=i,e[t+1]=o}var t=this.P.map(t=>t.C());return new u(e,t)}B(){var t,r=new Set;for(t of this.P)for(var e of t.L())for(var i of e.R)r.add(i);var o,a=[];for(o of r){var n=this.G[2*o],s=this.G[2*o+1];a.push({W:o,x:n,y:s})}a.sort((t,r)=>t.x!==r.x?t.x-r.x:t.y!==r.y?t.y-r.y:t.W-r.W);var l,h=new Map,f=[];for(let t=0;t<a.length;t++){var{W:c,x:v,y:d}=a[t];h.set(c,t),f.push(`QUBIT_COORDS(${v}, ${d}) `+t)}for(l of this.P){var w,u=S(l.L(),t=>{let r=t.Z.name;return 0<t.Y.length&&(r+="("+[...t.Y].join(",")+")"),r}),X=[...u.keys()];X.sort((t,r)=>{var e=t.startsWith("MARK")||t.startsWith("POLY"),i=r.startsWith("MARK")||r.star)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(tsWith("POLY");return e!==i?e<i?-1:1:t<r?-1:r<t?1:0});for(w of X){var Z,Y=u.get(w),R=[];if(k.get(w.split("(")[0]).o){var y,M=[];for(y of Y)M.push(...y.R);R.push(M)}else for(var I of Y)R.push([...I.R]);for(Z of R){var m,p=[w];for(m of Z)p.push(h.get(m));f.push(p.join(" "))}}f.push("TICK")}for(;0<f.length&&"TICK"===f[f.length-1];)f.pop();return f.join("\n")}V(t){var r,e,i=this.j(),o=[];for([r,e]of t){var a=r+","+e;i.has(a)||(i.set(a,i.size),o.push(r,e))}return new u(new Float64Array([...this.G,...o]),this.P.map(t=>t.C()))}j(){var r=new Map;for(let t=0;t<this.G.length;t+=2){var e=this.G[t],i=this.G[t+1];r.set(e+","+i,t/2)}return r}toString(){return this.B()}J(t){return t instanceof u&&this.B()===t.B()}}const v=1e3,O=(new function(){}).toString(),T="!recursion-limit!";function x(t,r){if(0===r)return T;if(t instanceof Map){var e,i,o=r,a=[];for([e,i]of t.entries()){if(a.length>v){a.push("[...]");break}e=w(e,o-1),i=w(i,o-1);a.push(e+": "+i)}return`Map{${a.join(", ")}}`}if(t instanceof Set){var n,s=r,l=[];for(n of t))CRUMBLE_PART");
    result.append(R"CRUMBLE_PART({if(l.length>v){l.push("[...]");break}l.push(w(n,s-1))}return`Set{${l.join(", ")}}`}if(void 0!==t[Symbol.iterator]){var h,f=r,c=[];for(h of t){if(c.length>v){c.push("[...]");break}c.push(w(h,f-1))}return`${t=Array.isArray(t)?"":t.constructor.name}[${c.join(", ")}]`}}function K(t,r){try{var e=String(t);if(e!==O)return e}catch{}var i=t,o=r,a=[];for(s in i)if(i.hasOwnProperty(s)){if(a.length>v){a.push("[...]");break}var n=i[s],s=w(s,o-1),n=w(n,o-1);a.push(s+": "+n)}return void 0===i.constructor?"[an unknown non-primitive value with no constructor]":(e=(e=i.constructor.name)==={}.constructor.name?"":`(Type: ${e})`)+`{${a.join(", ")}}`}function w(t,r=10){return(null===(e=t)?"null":void 0===e?"undefined":"string"==typeof e?`"${e}"`:"number"==typeof e?""+e:void 0)||x(t,r)||K(t,r);var e}function X(t,r){if(t===r||G(t)&&G(r))return!0;var e,i=function(t,r){if(!Z(t)&&void 0!==t.constructor&&t.constructor.prototype.hasOwnProperty("J"))return t.J(r);if(!Z(r)&&void 0!==r.constructor&&r.constructor.prototype.hasOwnProperty(")CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(J"))return r.J(t)}(t,r);if(void 0!==i)return i;if(Z(t)||Z(r)||t.constructor.name!==r.constructor.name)return!1;if(t instanceof Map){var o,a,i=t,n=r;if(i.size!==n.size)return!1;for([o,a]of i){if(!n.has(o))return!1;o=n.get(o);if(!X(a,o))return!1}return!0}if(t instanceof Set)return P(t,r);if(e=t,Array.isArray(e)||!L.every(t=>!(e instanceof t))){var s=t,l=r;if(s.length!==l.length)return!1;for(let t=0;t<s.length;t++)if(!X(s[t],l[t]))return!1;return!0}var h,f=t,c=r;if(!P(i=D(f),D(c)))return!1;for(h of i)if(h!==Symbol.iterator&&!X(f[h],c[h]))return!1;i=void 0!==f[Symbol.iterator],t=void 0!==c[Symbol.iterator];return i==t&&!(i&&t&&!function(t,r){var e=r[Symbol.iterator]();for(var i of t){var o=e.next();if(o.done||!X(i,o.value))return}return e.next().done}(f,c))}const L=[Float32Array,Float64Array,Int8Array,Int16Array,Int32Array,Uint8Array,Uint16Array,Uint32Array,Uint8ClampedArray];function G(t){return"number"==typeof t&&isNaN(t)}function Z(t){return null==t||"string"==typeof t||"number"==typeof t||"boolean"==typeof t})CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(function P(t,r){if(t.size!==r.size)return!1;for(var e of t)if(!r.has(e))return!1;return!0}function D(t){var r,e=new Set;for(r in t)t.hasOwnProperty(r)&&e.add(r);return e}class Q{constructor(t,r,e,i,o,a){this.tt=t,this.rt=r,this.altKey=e,this.shiftKey=a,this.ctrlKey=i,this.metaKey=o}J(t){return t instanceof Q&&this.tt===t.tt&&X(this.rt,t.rt)&&this.altKey===t.altKey&&this.shiftKey===t.shiftKey&&this.ctrlKey===t.ctrlKey&&this.metaKey===t.metaKey}toString(){return`ChordEvent(
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    inProgress=${this.tt},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    chord=${w(this.rt)},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    altKey=${this.altKey},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    shiftKey=${this.shiftKey},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    ctrlKey=${this.ctrlKey},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(    metaKey=${this.metaKey},
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART()`}}const F=new Set(["alt","shift","control","meta"]);class N{constructor(){this.et=new Set,this.it=new Set,this.ot=new Set,this.nt=[]}st(t){return new Q(t,new Set(this.ot),this.et.has("alt"),this.et.has("control"),this.et.has("meta"),this.et.has("shift"))}lt(t){this.nt.push(this.st(t))}ht(){this.it.clear(),this.ot.clear(),this.et.clear()}ft(t){var r,e,i=t.key.toLowerCase();if("escape"===i&&this.ht(),"keydown"===t.type){for([r,e]of[[t.altKey,"alt"],[t.shiftKey,"shift"],[t.ctrlKey,"control"],[t.metaKey,"meta"]])r?this.et.add(e):this.et.delete(e);F.has(i)||(this.it.add(i),this.ot.add(i)),this.lt(!0)}else{if("keyup"!==t.type)throw new Error("Not a recognized key event type: "+t.type);F.has(i)||(this.it.delete(i),this.lt(0<this.it.size),0===this.it.size&&(this.et.clear(),this.ot.clear()))}}}class W{constructor(t,r,e=0,i=!1){this.action=t,this.ct=r,this.vt=e,this.dt=i,this.wt="idle",this.ut=-1/0}Xt(){var t=this.ct-(performance.now()-this.ut);if(0<t)this.Zt(t);else{this.wt="running";t=performance.now();try{this.act)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ion()}finally{t=performance.now()-t;this.ut=performance.now()+t*this.vt,"running-and-triggered"===this.wt?this.Zt(this.ct):this.wt="idle"}}}Yt(){switch(this.wt){case"idle":this.Xt();break;case"waiting":break;case"running":this.wt="running-and-triggered";break;case"running-and-triggered":break;default:throw new Error("Unrecognized throttle state: "+this.wt)}}Zt(e){if(this.wt="waiting",this.dt){let t,r=performance.now();(t=()=>{performance.now()<r+e?requestAnimationFrame(t):(this.wt="idle",this.ut=-1/0,this.Yt())})()}else setTimeout(()=>{this.wt="idle",this.ut=-1/0,this.Yt()},e)}}class f{constructor(t){this.Rt=t}subscribe(t){return this.Rt(t)}static of(...e){return new f(t=>{for(var r of e)t(r);return()=>{}})}yt(){let r=[];return this.subscribe(t=>r.push(t))(),r}map(e){return new f(r=>this.subscribe(t=>r(e(t))))}filter(e){return new f(r=>this.subscribe(t=>{e(t)&&r(t)}))}Mt(s,l){return new f(r=>{let e=!1,i=!1,o,a,t=this.subscribe(t=>{o=t,e=!0,i&&r(l(o,a))}),n=s.subscribe(t=>{a=t,i=!0,e&&r(l(o,a))});return()=>{t()CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(),n()}})}static It(){return new f(t=>{let r,e=!1;return(r=()=>{e||(t(void 0),window.requestAnimationFrame(r))})(),()=>{e=!0}})}bt(){return new f(e=>{let i=()=>{},o=!1,t=this.subscribe(t=>{var r;o||(r=i,i=t.subscribe(e),r())});return()=>{o=!0,i(),t()}})}kt(r){return this.map(t=>(r(t),t))}At(){return new f(r=>{let e=[];return e.push(this.subscribe(t=>e.push(t.subscribe(r)))),()=>{for(var t of e)t()}})}Et(a){return new f(t=>{let r=void 0,e=!1,i=new W(()=>{e||t(r)},a),o=this.subscribe(t=>{r=t,i.Yt()});return()=>{e=!0,o()}})}static Ct(r,e){return new f(t=>(r.addEventListener(e,t),()=>r.removeEventListener(e,t)))}_t(t){return new f(r=>{let e=t;return this.subscribe(t=>{0<e?--e:r(t)})})}gt(t=void 0){let o=t||((t,r)=>t===r);return new f(r=>{let e=!1,i=void 0;return this.subscribe(t=>{e&&o(i,t)||(i=t,e=!0,r(t))})})}}class V{constructor(){this.St=[],this.Ot=new f(t=>{this.St.push(t);let r=!1;return()=>{r||(r=!0,this.St.splice(this.St.indexOf(t),1))}})}Tt(){return this.Ot}send(t){for(var r of this.St)r(t)}}class j{const)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ructor(t=void 0){this.xt=t,this.Kt=new V,this.Ot=new f(t=>(t(this.xt),this.Kt.Tt().subscribe(t)))}Tt(){return this.Ot}set(t){this.xt=t,this.Kt.send(t)}get(){return this.xt}}class r{constructor(t,r,e){if(r<0||r>=t.length)throw new Error("Bad index: "+{history:t,index:r,Lt:e});if(!Array.isArray(t))throw new Error("Bad history: "+{history:t,index:r,Lt:e});this.history=t,this.index=r,this.Lt=e,this.Gt=new V,this.Pt=new j(this.history[this.index])}Dt(){return this.Gt.Tt()}Qt(){return this.Pt.Tt()}Ft(){return this.Pt.get()}static Nt(t){return new r([t],0,!1)}Ut(){return 0===this.index&&!this.Lt}zt(){return this.index===this.history.length-1}clear(t){this.history=[t],this.index=0,this.Lt=!1,this.Pt.set(t),this.Gt.send(t)}Ht(){this.Lt=!0,this.Gt.send(void 0)}$t(){this.Lt=!1;var t=this.history[this.index];return this.Pt.set(t),this.Gt.send(t),t}commit(t){t===this.history[this.index]?this.$t():(this.Lt=!1,this.index+=1,this.history.splice(this.index,this.history.length-this.index),this.history.push(t),this.Pt.set(t),th)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(is.Gt.send(t))}qt(){if(!this.Lt){if(0===this.index)return;--this.index}this.Lt=!1;var t=this.history[this.index];return this.Pt.set(t),this.Gt.send(t),t}Bt(){var t;if(this.index+1!==this.history.length)return this.index+=1,this.Lt=!1,t=this.history[this.index],this.Pt.set(t),this.Gt.send(t),t}toString(){return"Revision("+w({index:this.index,count:this.history.length,Wt:this.Lt,head:this.history[this.index]})+")"}J(t){return t instanceof r&&this.index===t.index&&this.Lt===t.Lt&&X(this.history,t.history)}}let lt=32;function J(i,o,a,n){var t,r=i.canvas.width/2,e=o.Vt();e.sort((t,r)=>{var[t,e]=n(t),[r,i]=n(r);return e!==i?e-i:t-r});let s=new Map,l=void 0,h=0,f=0,c=0,v=0;for(t of e){var[K,d]=n(t);f+=lt,l!==d?(l=d,h=1.5*r,c=Math.max(c,v),v=0,f+=.25*lt):(h+=.25*nt,v++),s.set(K+","+d,[h,f])}let w=lt+nt*c*.25,u=(t,r)=>{var[t,e]=n(t);return[t,e,r]=[[t,e,r]][0],t=t+","+e,s.has(t)?([e,t]=s.get(t),[e+(r-o.jt)*w,t]):[void 0,void 0]};var X=Math.floor(i.canvas.width/4/w),Z=Math.max(0,o.jt-X+1),Y=o.jt+X+2;i.save();try{i.clear)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(Rect(r,0,r,i.canvas.height);for(let t=0;t<a.length;t++)if(t<4){R=void 0;y=void 0;M=void 0;I=void 0;m=void 0;L=void 0;G=void 0;_=void 0;g=void 0;S=void 0;p=void 0;b=void 0;O=void 0;T=void 0;k=void 0;P=void 0;D=void 0;Q=void 0;F=void 0;A=void 0;E=void 0;C=void 0;var R=i;var y=u;var M=a[t];var I=t;var m=Z;var L=Y;var G=w;let r,e;e=G,0===I?r=10:1===I?r=5:2===I?r=0:3===I&&(r=-5);for(let t=m;t<=L;t++){var p,b,k,A,E,C,_=M.Jt(t);for([p,b]of _.tr.entries()){var[g,S]=y(p,t);if(void 0!==g&&void 0!==S){if("X"===b)R.fillStyle="red";else if("Y"===b)R.fillStyle="green";else{if("Z"!==b)throw new Error("Not a pauli: "+b);R.fillStyle="blue"}R.fillRect(+g,S-r,e,5)}}for(k of _.rr){var[O,T]=y(k,t-.5);void 0!==O&&void 0!==T&&(R.fillStyle="magenta",R.fillRect(+O-8,T-r-8,e+16,21),R.fillStyle="black",R.fillRect(+O,T-r,e,5))}for({er:A,ir:E,color:C}of _.ar){var[P,D]=y(A,t),[Q,F]=y(E,t);"X"===C?R.strokeStyle="red":"Y"===C?R.strokeStyle="green":"Z"===C?R.strokeStyle="blue":R.strokeStyle="magenta",R.lineWidth=8,st(R,P,D,Q,F),R.lineWidth=1)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(}}}i.globalAlpha*=.5,i.fillStyle="black",i.fillRect(1.5*r-1.3*nt,0,w,i.canvas.height),i.globalAlpha*=2,i.strokeStyle="black",i.fillStyle="black";for(var N of e){var[U,z]=u(N,Z-1),[H,$]=u(N,Y+1);i.beginPath(),i.moveTo(U,z),i.lineTo(H,$),i.stroke()}i.textAlign="right",i.textBaseline="middle";for(var x of e){var[q,B]=u(x,Z-1),W=o.nr.G[2*x],V=o.nr.G[2*x+1];i.fillText(W+`,${V}:`,q,B)}for(let r=Z;r<=Y;r++){var j=t=>u(t,r),J=o.nr.P[r];if(void 0!==J)for(var tt of J.L())tt.I(j,i)}i.globalAlpha=.25,i.setLineDash([1,1]);let t=0;for(var rt of e)t=Math.max(t,n(rt)[0]);for(var et of e){var[it,ot]=u(et,Z-1),[,at]=n(et);i.beginPath(),i.moveTo(it,ot),i.lineTo(t+.25,at),i.stroke()}}finally{i.restore()}}class tt{constructor(t,r,e){this.tr=t,this.rr=r,this.ar=e}}class rt{constructor(t){this.sr=t}Jt(t){let r=this.sr.get(t);return r=void 0===r?new tt(new Map,new Set,[]):r}static lr(r,e){var i=new rt(new Map);let o=new Map;for(let t=0;t<r.P.length;t++){var a,n=r.P[t],s=o,l=(o=n.S(o,e),new Set);for(a of[...o.keys()]){var h=o.get(a);)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(h.startsWith("ERR:")&&(l.add(a),o.set(a,h.substring(4))),"I"===o.get(a)&&o.delete(a)}var f,c=[];for(f of n.L())if(2===f.Z.t&&!f.Z.i){var v,[d,w]=f.R,u=new Set;for(v of f.R){var X=o.get(v),Z=s.get(v);X!==Z&&(void 0!==X&&u.add(X),void 0!==Z)&&u.add(Z)}if(0<u.size){let t="I";1===u.size&&(t=[...u][0]),c.push({er:d,ir:w,color:t})}}(0<o.size||0<l.size||0<c.size)&&i.sr.set(t,new tt(o,l,c))}return i}}const z=-d+Math.floor(d/4)+.5,H=-d+Math.floor(d/4)+.5;function $(t,r){var e,i,o,a;return void 0!==t&&void 0!==r&&(e=t/d,i=r/d,e=Math.floor(2*e+.5)/2,i=Math.floor(2*i+.5)/2,o=e*d,a=i*d,Math.abs(o-t)<=nt)&&Math.abs(a-r)<=nt&&e%1==i%1?[e,i]:[void 0,void 0]}let et=!0;function q(t,r){t.save();try{et&&r()}finally{t.restore()}}function it(L,G){let P=G.nr,r=0;for(var t of P.P)for(var e of t.A){var i=e.Z;"MARKX"!==i.name&&"MARKY"!==i.name&&"MARKZ"!==i.name||(r=Math.max(r,e.Y[0]+1))}let D=(t,r)=>[t*d-z,r*d-H],Q=t=>{var r=P.G[2*t],t=P.G[2*t+1];return D(r,t)},F=[];for(let t=0;t<r;t++)F.push(rt.lr(P,t));let N=new Set;for(var o of P.F)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(()){var a=P.G[2*o],o=P.G[2*o+1];N.add(a+","+o)}q(L,()=>{L.fillStyle="white",L.clearRect(0,0,L.canvas.width,L.canvas.height);var[t,r]=$(G.hr,G.cr);let e=G.jt;for(let t=0;t<=G.jt;t++)for(var K of P.P[t].A)if("POLYGON"===K.Z.name){e=t;break}var i,o,a=[...P.P[e].A];a.sort((t,r)=>r.R.length-t.R.length);for(i of a)"POLYGON"===i.Z.name&&i.I(Q,L);q(L,()=>{P.F();L.strokeStyle="black";for(let r=0;r<100;r+=.5)for(let t=r%1;t<100;t+=1){var[e,i]=D(r,t),o=(r%1==.5?L.fillStyle="pink":L.fillStyle="white",!N.has(r+","+t));o&&(L.globalAlpha*=.25),L.fillRect(e-nt,i-nt,2*nt,2*nt),L.strokeRect(e-nt,i-nt,2*nt,2*nt),o&&(L.globalAlpha*=4)}});for(let t=0;t<F.length;t++){v=c=f=w=d=h=l=s=n=void 0;var n=L,s=G,l=Q,h=F[t];if(t,void 0!==(h=h.Jt(s.jt).ar))for(var{er:f,ir:c,color:v}of h){var[f,d]=l(f),[c,w]=l(c);"X"===v?n.strokeStyle="red":"Y"===v?n.strokeStyle="green":"Z"===v?n.strokeStyle="blue":n.strokeStyle="magenta",n.lineWidth=8,st(n,f,d,c,w),n.lineWidth=1}}for(o of P.P[G.jt].L())"POLYGON"!==o.Z.name&&o.I(Q,L);q(L,()=>{L.globalAlpha*=.)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(25;for(var[t,r]of G.vr.values()){var[t,r]=D(t,r);L.fillStyle="yellow",L.fillRect(t-1.25*nt,r-1.25*nt,2.5*nt,2.5*nt)}}),q(L,()=>{L.globalAlpha*=.5;for(var[t,r]of G.dr.values()){var[t,r]=D(t,r);L.fillStyle="blue",L.fillRect(t-1.25*nt,r-1.25*nt,2.5*nt,2.5*nt)}});for(let t=0;t<F.length;t++){Z=x=T=O=S=g=C=E=_=X=u=A=k=b=p=m=I=M=y=R=Y=void 0;var u,X,Z,Y=L,R=G,y=Q,M=F[t],I=t,{dx:m,dy:p,m:b,p:k}=U(I),A=[];for([u,X]of M.Jt(R.jt).tr.entries())A.push([X,y(u)]);if(0<A.length){A.every(t=>"X"===t[0])?Y.fillStyle="red":A.every(t=>"Y"===t[0])?Y.fillStyle="green":A.every(t=>"Z"===t[0])?Y.fillStyle="blue":Y.fillStyle="black",Y.strokeStyle=Y.fillStyle;var E,C,_=A.map(t=>t[1]);let n=0,s=0;for([E,C]of _)n+=E,s+=C;n/=_.length,s/=_.length,_.sort((t,r)=>{var[t,e]=t,[r,i]=r;let o=Math.atan2(e-s,t-n),a=Math.atan2(i-s,r-n);return t===n&&e===s&&(o=-100),r===n&&i===s&&(a=-100),o-a}),B(Y,_),Y.globalAlpha*=.25,Y.fill(),Y.globalAlpha*=4,Y.lineWidth=3,Y.stroke(),Y.lineWidth=1}if(I<4)for(var[g,[S,O]]of A){if("X"===g)Y.fillStyle="red";else if(")CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(Y"===g)Y.fillStyle="green";else{if("Z"!==g)throw new Error("Not a pauli: "+g);Y.fillStyle="blue"}Y.fillRect(S-m,O-p,b,k)}for(Z of M.Jt(R.jt).rr){var[T,x]=y(Z);Y.fillStyle="magenta",Y.fillRect(T-m-8,x-p-8,b+16,k+16),Y.fillStyle="black",Y.fillRect(T-m,x-p,b,k)}}void 0!==t&&(L.save(),L.globalAlpha*=.5,[a,t]=D(t,r),L.fillStyle="red",L.fillRect(a-nt,t-nt,2*nt,2*nt),L.restore()),q(L,()=>{var t,r,e,i,o,a;L.globalAlpha*=.25,L.fillStyle="blue",void 0!==G.wr&&void 0!==G.hr&&(t=Math.min(G.hr,G.wr),r=Math.max(G.hr,G.wr),e=Math.min(G.cr,G.ur),i=Math.max(G.cr,G.ur),--t,r+=1,--e,i+=1,t-=z,r-=z,e-=H,i-=H,L.fillRect(t,e,r-t,i-e));for([o,a]of G.Xr){var[n,s]=D(o,a);L.fillRect(n-nt,s-nt,2*nt,2*nt)}})}),L.save();try{L.strokeStyle="black";for(let r=0;r<P.P.length;r++){var n=!F.every(t=>0===t.Jt(r).rr.size);r===G.jt?L.fillStyle="red":(n&&(L.fillStyle="magenta",L.fillRect(-2,5*r-2,14,8)),L.fillStyle="black"),L.fillRect(0,5*r,10,4)}}finally{L.restore()}J(L,G,F,Q)}class ot{constructor(t,r,e,i,o,a,n,s,l){for(this.nr=t.C(),this.jt=r,thi)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(s.dr=new Map(e.entries()),this.vr=new Map(i.entries()),this.hr=o,this.cr=a,this.wr=n,this.ur=s,this.Xr=[...l];this.nr.P.length<=this.jt;)this.nr.P.push(new A)}Zr(){return this.nr.F()}Vt(){let r=this.Zr();var t=[];if(0<this.vr.size){var e,i=this.nr.j();for(e of this.vr.keys()){var o=i.get(e);void 0!==o&&t.push(o)}}else t.push(...r.values());return t.filter(t=>r.has(t))}}function at(r){let e=[1,0],i=[0,1];var o=(t,r)=>[t-r,t+r];r=(r%8+8)%8;for(let t=0;t<r;t++)e=o(e[0],e[1]),i=o(i[0],i[1]);return(t,r)=>[e[0]*t+i[0]*r,e[1]*t+i[1]*r]}function ht(){try{return window.self===window.top}catch(t){}}class ft{constructor(){this.Yr=!1,this.Rr=void 0}yr(){this.Rr={Mr:!0}}Ir(t){this.Rr=t}mr(){this.Rr=void 0}pr(t,r){if(!r.startsWith("#"))throw new Error('"Expected a hash URL: '+{br:t,kr:r});if(ht()&&this.Rr!==t)if(this.Yr)document.location.hash=r;else try{void 0===this.Rr?history.replaceState(t,"",r):(history.pushState(t,"",r),this.Rr=void 0)}catch(t){console.warn("Calling 'history.replaceState/pushState' failed. Falling bac)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(k to setting location.hash.",t),this.Yr=!0,document.location.hash=r}}}function ct(t){return"#circuit="+(t=-1===(t=t.replaceAll("QUBIT_COORDS","Q").replaceAll(", ",",").replaceAll(") ",")").replaceAll(" ","_").replaceAll("\n",";")).indexOf("%")&&-1===t.indexOf("&")?t:encodeURIComponent(t))}let c=document.getElementById("toolbox"),R=10.5,y=["H","S","R","M","C","1","2","3","4"],vt=[1,2,2,2,void 0,-1,-1,-1,-1];let dt=new Map([["0,0",k.get("H_YZ")],["0,1",k.get("H")],["0,2",k.get("H_XY")],["1,0",k.get("SQRT_X")],["1,1",k.get("SQRT_Y")],["1,2",k.get("S")],["2,0",k.get("RX")],["2,1",k.get("RY")],["2,2",k.get("R")],["3,0",k.get("MX")],["3,1",k.get("MY")],["3,2",k.get("M")],["4,0",k.get("CX")],["4,1",k.get("CY")],["4,2",k.get("CZ")],["5,0",k.get("MARKX").X(0)],["5,1",k.get("MARKY").X(0)],["5,2",k.get("MARKZ").X(0)],["6,0",k.get("MARKX").X(1)],["6,1",k.get("MARKY").X(1)],["6,2",k.get("MARKZ").X(1)],["7,0",k.get("MARKX").X(2)],["7,1",k.get("MARKY").X(2)],["7,2",k.get("MARKZ").X(2)],["8,0",k.get("MARKX").X(3)],["8,1",k.g)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(et("MARKY").X(3)],["8,2",k.get("MARKZ").X(3)],["5,-1",k.get("MARK").X(0)],["6,-1",k.get("MARK").X(1)],["7,-1",k.get("MARK").X(2)],["8,-1",k.get("MARK").X(3)]]);function wt(t){var r,e=function(t){var r,e;if(!t.ctrlKey)return r=+t.rt.has("x"),e=+t.rt.has("y"),t=+t.rt.has("z"),r&&!e&&!t||!r&&e&&t?{Ar:0,strength:Math.max(r,Math.min(e,t))}:!r&&e&&!t||r&&!e&&t?{Ar:1,strength:Math.max(e,Math.min(r,t))}:!r&&!e&&t||r&&e&&!t?{Ar:2,strength:Math.max(t,Math.min(r,e))}:void 0}(t),t=function(e){if(!e.ctrlKey){let r=void 0;for(let t=0;t<y.length;t++){var i=e.rt.has(y[t].toLowerCase());0<i&&(void 0===r||i>r.strength)&&(r={Er:t,strength:i})}return r}}(t);let i=e,o=(void 0!==t&&void 0===e&&(r=vt[t.Er],i=void 0===r?void 0:{strength:0,Ar:r}),void 0);return void 0!==i&&void 0!==t&&(r=t.Er+","+i.Ar,dt.has(r))&&(o=dt.get(r)),{Cr:e,_r:i,gr:t,Sr:o}}const e=-d+Math.floor(d/4)+.5,o=-d+Math.floor(d/4)+.5;var ut=document.getElementById("btnUndo"),Xt=document.getElementById("btnRedo"),Zt=document.getElementById("btnClearMarkers");const M=)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(document.getElementById("btnShowHideImportExport");var Yt=document.getElementById("btnNextLayer"),Rt=document.getElementById("btnPrevLayer"),yt=document.getElementById("btnRotate45"),Mt=document.getElementById("btnRotate45Counter"),t=document.getElementById("btnExport"),It=document.getElementById("btnImport"),mt=document.getElementById("clear");const I=document.getElementById("txtStimCircuit");I.addEventListener("keyup",t=>t.stopPropagation()),I.addEventListener("keydown",t=>t.stopPropagation());let m=new class{constructor(t){this.rev=r.Nt(""),this.canvas=t,this.cr=void 0,this.hr=void 0,this.Or=new N,this.jt=0,this.dr=new Map,this.vr=new Map,this.wr=void 0,this.ur=void 0,this.Tr=new j(this.Kr(void 0))}Lr(){for(var t=u.D(this.rev.Ft());t.P.length<=this.jt;)t.P.push(new A);return t}Gr(){this.dr.clear(),this.Pr()}Dr(t){var r,e=this.Lr(),i=e.j();for(r of this.dr.keys()){var o=i.get(r);void 0!==o&&e.P[this.jt].T(o)}this.Qr(e,t)}Fr(t){var r=this.Lr();r.P.splice(this.jt,1),this.Qr(r,t)}Nr(t){var r=this.Lr();r.P.spli)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ce(this.jt,0,new A),this.Qr(r,t)}qt(){this.rev.qt()}Bt(){this.rev.Bt()}Qr(t,r){r?this.Ur(t):this.commit(t)}commit(t){for(;0<t.P.length&&t.P[t.P.length-1].O();)t.P.pop();this.rev.commit(t.B())}Ur(t){this.rev.Ht(),this.Tr.set(this.Kr(t))}Kr(t){return void 0===t&&(t=this.Lr()),new ot(t,this.jt,this.dr,this.vr,this.hr,this.cr,this.wr,this.ur,this.zr(this.Or.et.has("alt")))}Pr(){var t=this.Tr.get().nr;this.Tr.set(this.Kr(t))}Hr(){this.commit(new u(new Float64Array([]),[]))}$r(){var t,r=this.Lr();for(t of r.P)t.A=t.A.filter(t=>"MARKX"!==t.Z.name&&"MARKY"!==t.Z.name&&"MARKZ"!==t.Z.name);this.commit(r)}zr(i){var t=this.hr,r=this.cr,o=this.wr,a=this.ur,n=[];if(void 0!==t&&void 0!==o){var[s,l]=$(o,a),h=Math.min(t,o),f=Math.max(t,o),c=Math.min(r,a),v=Math.max(r,a),t=d/4-nt;h+=t,f-=t,c+=t,v-=t,h=Math.floor(2*h/d+.5)/2,f=Math.floor(2*f/d+.5)/2,c=Math.floor(2*c/d+.5)/2,v=Math.floor(2*v/d+.5)/2;let e=1;h!=f&&c!=v||(e=2);for(let r=h;r<=f;r+=.5)for(let t=c;t<=v;t+=.5)r%1!=t%1||i&&(s%e!=r%e||l%e!=t%e)||n.push([r,t])}return n}q)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(r(o,t){let r=this.Lr();var e;r=r.U(o),t||(this.vr=(e=t=>{var r,e,i=new Map;for([r,e]of t.values())[r,e]=o(r,e),i.set(r+","+e,[r,e]);return i})(this.vr),this.dr=e(this.dr)),this.Qr(r,t)}Br(t,r){let e=at(t),i=this.Lr().U(e).H();this.qr((t,r)=>([t,r]=e(t,r),i(t,r)),r)}Wr(t){this.jt=Math.max(t,0),this.Pr()}Vr(t,r,e){r||e||this.dr.clear();for(var[i,o]of t){var a=i+","+o;e&&this.dr.has(a)?this.dr.delete(a):this.dr.set(a,[i,o])}this.Pr()}jr(t,r){var e,i=this.Lr().V(this.dr.values()),o=i.j(),a=new Set;for(e of this.dr.keys())a.add(o.get(e));var n,s=new Map,l=i.P[this.jt];for(n of[...a]){var h=l.k.get(n);if(void 0!==h)if("RX"===h.Z.name||"MX"===h.Z.name||"MRX"===h.Z.name)s.set(n,"X");else if("RY"===h.Z.name||"MY"===h.Z.name||"MRY"===h.Z.name)s.set(n,"Y");else if("R"===h.Z.name||"M"===h.Z.name||"MR"===h.Z.name)s.set(n,"Z");else if("MXX"===h.Z.name||"MYY"===h.Z.name||"MZZ"===h.Z.name){var f,c=h.Z.name[1];for(f of h.R)s.set(f,c),a.add(f)}}var v,d=new Set(s.values());d.delete(void 0);let w;w=1===d.size?[...d][0]:"Z";for(v)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART( of a){let t=s.get(v);void 0===t&&(t=w);var u=k.get("MARK"+t).X(r);l.put(new b(u,new Float32Array([r]),new Uint32Array([v])))}this.Qr(i,t)}Jr(t,r,e){var i,o=this.Lr().V(this.dr.values()),a=o.j();for(i of this.dr.keys())o.P[this.jt].put(new b(r,new Float32Array(e),new Uint32Array([a.get(i)])));this.Qr(o,t)}te(t,r,e){let i=this.Lr();var[o,a]=$(this.hr,this.cr),[n,s]=Y(this.dr.values());if(void 0!==o&&void 0!==n&&!this.dr.has(o+","+a)){var l,h,f=o-n,c=a-s,v=[];for([l,h]of this.dr.values())v.push([l,h]),v.push([l+f,h+c]);var d=(i=i.V(v)).j();for(let t=0;t<v.length;t+=2){var[w,u]=v[t],[X,Z]=v[t+1],w=d.get(w+","+u),u=d.get(X+","+Z);i.P[this.jt].put(new b(r,new Float32Array(e),new Uint32Array([w,u])))}}this.Qr(i,t)}re(t,r,e){if(0!==this.dr.size){var i,n=[];let o=0,a=0;for(i of this.dr.values())n.push(i),o+=i[0],a+=i[1];o/=n.length,a/=n.length,n.sort((t,r)=>{var[t,e]=t,[r,i]=r;return Math.atan2(e-a,t-o)-Math.atan2(i-a,r-o)});var s=this.Lr().V(this.dr.values()),l=s.j(),h=new Uint32Array(this.dr.size);for(let t=0;t<n.l)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ength;t++){var[f,c]=n[t];h[t]=l.get(f+","+c)}s.P[this.jt].put(new b(r,new Float32Array(e),h)),this.Qr(s,t)}}ee(t,r,e=void 0){void 0===e&&(e=void 0===r.u?[]:[r.u]),1===r.t?this.Jr(t,r,e):2===r.t?this.te(t,r,e):this.re(t,r,e)}}(document.getElementById("cvn"));function pt(){var t=m.Lr().B().replaceAll("\nPOLYGON","\n#!pragma POLYGON").replaceAll("\nMARK","\n#!pragma MARK"),r=I;r.value=t+"\n",r.focus(),r.select()}t.addEventListener("click",t=>{pt()}),It.addEventListener("click",t=>{var r=I.value,r=u.D(r.replaceAll("\n#!pragma ","\n"));m.commit(r)}),M.addEventListener("click",t=>{var r=document.getElementById("divImportExport");"none"===r.style.display?(r.style.display="block",M.textContent="Hide Import/Export",pt()):(r.style.display="none",M.textContent="Show Import/Export",I.value=""),setTimeout(()=>{window.scrollTo(0,0)},0)}),mt.addEventListener("click",t=>{m.Hr()}),ut.addEventListener("click",t=>{m.qt()}),Xt.addEventListener("click",t=>{m.Bt()}),Zt.addEventListener("click",t=>{m.$r()}),yt.addEventListener("cli)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ck",t=>{m.Br(1,!1)}),Mt.addEventListener("click",t=>{m.Br(-1,!1)}),Yt.addEventListener("click",t=>{m.Wr(m.jt+1)}),Rt.addEventListener("click",t=>{m.Wr(m.jt-1)}),window.addEventListener("resize",t=>{m.canvas.width=m.canvas.scrollWidth,m.canvas.height=m.canvas.scrollHeight,m.Pr()}),m.canvas.addEventListener("mousemove",t=>{m.hr=t.offsetX+e,m.cr=t.offsetY+o,m.wr-e<10&&m.hr-e<10&&1===t.buttons?(m.Wr(Math.floor(t.offsetY/5)),t.preventDefault()):m.Pr()}),m.canvas.addEventListener("mousedown",t=>{m.hr=t.offsetX+e,m.cr=t.offsetY+o,m.wr=t.offsetX+e,m.ur=t.offsetY+o,m.wr-e<10&&1===t.buttons?m.Wr(Math.floor(t.offsetY/5)):m.Pr()}),m.canvas.addEventListener("mouseup",t=>{var r=m.zr(t.altKey);m.wr=void 0,m.ur=void 0,m.hr=t.offsetX+e,m.cr=t.offsetY+o,m.Vr(r,t.shiftKey,t.ctrlKey)});let bt=void 0;async function kt(){let e=m.Lr();e.P=[e.P[m.jt]],0<m.dr.size&&(e.P[0]=e.P[0].g(t=>{var r=e.G[2*t],t=e.G[2*t+1];return m.dr.has(r+","+t)}),[r,t]=Y(m.dr.values()),e=e.q(-r,-t));var t,r=e.B();try{await navigator.clipboard.writeText(r),b)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(t=void 0}catch(t){bt=r,console.error(t)}}async function At(e){let i;try{i=await navigator.clipboard.readText()}catch(t){i=bt,console.error(t)}if(void 0!==i){let r=u.D(i);if(1!==r.P.length)throw new Error(i);let t=m.Lr();0<m.dr.size&&([o,a]=Y(m.dr.values()),r=r.q(o,a));var o,a,n=[];for(let t=0;t<r.G.length;t+=2)n.push([r.G[t],r.G[t+1]]);var s,l,h=(t=t.V(n)).j();for(s of m.dr.keys()){var f=h.get(s);void 0!==f&&t.P[m.jt].T(f)}for(l of r.P[0].L()){var c,v=[];for(c of l.R){var d=r.G[2*c],w=r.G[2*c+1];v.push(h.get(d+","+w))}t.P[m.jt].put(new b(l.Z,l.Y,new Uint32Array(v)))}m.Qr(t,e)}}const Et=function(){let o=new Map;o.set("shift+t",t=>m.Br(-1,t)),o.set("t",t=>m.Br(1,t)),o.set("escape",()=>m.Gr),o.set("delete",t=>m.Dr(t)),o.set("backspace",t=>m.Dr(t)),o.set("ctrl+delete",t=>m.Fr(t)),o.set("ctrl+insert",t=>m.Nr(t)),o.set("ctrl+backspace",()=>m.Fr),o.set("ctrl+z",t=>{t||m.qt()}),o.set("ctrl+y",t=>{t||m.Bt()}),o.set("ctrl+shift+z",t=>{t||m.Bt()}),o.set("ctrl+c",async t=>{t||await kt()}),o.set("ctrl+v",At),o.set("ctrl+x)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(",async t=>{await kt(),m.Dr(t)}),o.set("l",t=>{t||(m.vr=new Map(m.dr.entries()),m.Pr())}),o.set(" ",t=>{var r,e=m.Lr(),i=e.j();for(r of m.dr.keys()){var o=i.get(r);void 0!==o&&e.P[m.jt].K(o)}m.Qr(e,t)}),o.set("q",t=>{t||m.Wr(m.jt-1)}),o.set("e",t=>{t||m.Wr(m.jt+1)});for(let[t,r]of[["1",0],["2",1],["3",2],["4",3],["5",4],["6",5],["7",6],["8",7],["9",8],["0",9],["-",10],["=",11],["\\",12],["`",13]])o.set(""+t,t=>m.jr(t,r)),o.set(t+"+x",t=>m.ee(t,k.get("MARKX").X(r))),o.set(t+"+y",t=>m.ee(t,k.get("MARKY").X(r))),o.set(t+"+z",t=>m.ee(t,k.get("MARKZ").X(r)));function a(t,r,e=void 0){for(var i of t){if(o.has(i))throw new Error("Chord collision: "+i);o.set(i,t=>m.ee(t,k.get(r)))}void 0!==e&&a(t.map(t=>"shift+"+t),e)}return o.set("p",t=>m.ee(t,k.get("POLYGON"),[1,0,0,.5])),o.set("alt+p",t=>m.ee(t,k.get("POLYGON"),[0,1,0,.5])),o.set("shift+p",t=>m.ee(t,k.get("POLYGON"),[0,0,1,.5])),o.set("p+x",t=>m.ee(t,k.get("POLYGON"),[1,0,0,.5])),o.set("p+y",t=>m.ee(t,k.get("POLYGON"),[0,1,0,.5])),o.set("p+z",t=>m.ee(t,k.get("POLYG)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ON"),[0,0,1,.5])),o.set("p+x+y",t=>m.ee(t,k.get("POLYGON"),[1,1,0,.5])),o.set("p+x+z",t=>m.ee(t,k.get("POLYGON"),[1,0,1,.5])),o.set("p+y+z",t=>m.ee(t,k.get("POLYGON"),[0,1,1,.5])),o.set("p+x+y+z",t=>m.ee(t,k.get("POLYGON"),[1,1,1,.5])),a(["h","h+y","h+x+z"],"H","H"),a(["h+z","h+x+y"],"H_XY","H_XY"),a(["h+x","h+y+z"],"H_YZ","H_YZ"),a(["s+x","s+y+z"],"SQRT_X","SQRT_X_DAG"),a(["s+y","s+x+z"],"SQRT_Y","SQRT_Y_DAG"),a(["s","s+z","s+x+y"],"S","S_DAG"),a(["r+x","r+y+z"],"RX"),a(["r+y","r+x+z"],"RY"),a(["r","r+z","r+x+y"],"R"),a(["m+x","m+y+z"],"MX"),a(["m+y","m+x+z"],"MY"),a(["m","m+z","m+x+y"],"M"),a(["m+r+x","m+r+y+z"],"MRX"),a(["m+r+y","m+r+x+z"],"MRY"),a(["m+r","m+r+z","m+r+x+y"],"MR"),a(["w"],"SWAP","SWAP"),a(["c+x"],"CX","CX"),a(["c+y"],"CY","CY"),a(["c+z"],"CZ","CZ"),a(["c+x+y"],"XCY","XCY"),a(["alt+c+x"],"XCX","XCX"),a(["alt+c+y"],"YCY","YCY"),a(["f"],"C_XYZ","C_ZYX"),a(["i"],"ISWAP","ISWAP_DAG"),a(["c+s+x"],"SQRT_XX","SQRT_XX_DAG"),a(["c+s+y"],"SQRT_YY","SQRT_YY_DAG"),a(["c+s+z"],"SQRT_ZZ","SQRT_ZZ_DAG"),a()CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(["c+m+x"],"MXX","MXX"),a(["c+m+y"],"MYY","MYY"),a(["c+m+z"],"MZZ","MZZ"),o}();function Ct(r){m.Or.ft(r);var t=m.Or.nt;if(0!==t.length){for(var e=t[t.length-1];0<t.length;)t.pop();var i=[...e.rt];if(0!==i.length){i.sort();let t="";e.altKey&&(t+="alt+"),e.ctrlKey&&(t+="ctrl+"),e.metaKey&&(t+="meta+"),e.shiftKey&&(t+="shift+");for(var o of i)t+=o+"+";t=t.substring(0,t.length-1);i=Et.get(t);void 0!==i?(i(e.tt),r.preventDefault()):m.Ur(m.Lr())}}}document.addEventListener("keydown",Ct),document.addEventListener("keyup",Ct),m.canvas.width=m.canvas.scrollWidth,m.canvas.height=m.canvas.scrollHeight,m.rev.Dt().subscribe(()=>{m.Tr.set(m.Kr(void 0));var t=m.Or.st(!1),e=(c.width=c.scrollWidth,c.height=c.scrollHeight,c.getContext("2d"));e.clearRect(0,0,c.width,c.height),e.textAlign="right",e.textBaseline="middle",e.fillText("X",7.5,24.5),e.fillText("Y",7.5,56.5),e.fillText("Z",7.5,88.5),e.textAlign="center",e.textBaseline="bottom";for(let t=0;t<y.length;t++)e.fillText(y[t],24.5+32*t,R);e.fillStyle="white",e.strokeStyle="bl)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(ack";var i=[["H_YZ","S_X","R_X","M_X","C_X","X1","X2","X3","X4"],["H","S_Y","R_Y","M_Y","C_Y","Y1","Y2","Y3","Y4"],["H_XY","S","R","M","C_Z","Z1","Z2","Z3","Z4"]];for(let r=0;r<y.length;r++)for(let t=0;t<3;t++)e.fillRect(R+32*r,R+32*t,28,28),e.strokeRect(R+32*r,R+32*t,28,28);e.fillStyle="black";for(let r=0;r<y.length;r++)for(let t=0;t<3;t++){var o,a,n=i[t][r],s=R+32*r+14,l=R+32*t+14;-1!==n.indexOf("_")?([o,a]=n.split("_"),e.font="16pt monospace",e.textAlign="right",e.textBaseline="middle",e.fillText(o,s,l),e.font=1===a.length?"12pt monospace":"8pt monospace",e.textAlign="left",e.textBaseline="top",e.fillText(a,s,l)):(e.font="16pt monospace",e.textAlign="center",e.textBaseline="middle",e.fillText(n,s,l))}performance.now(),void 0!==(t=wt(t)).Cr&&(e.fillStyle="rgba(255, 255, 0, "+.5*t.Cr.strength+")",e.fillRect(0,R+32*t.Cr.Ar-2,R+32*y.length,32)),void 0!==t.gr&&(e.fillStyle="rgba(255, 255, 0, "+.5*t.gr.strength+")",e.fillRect(R+32*t.gr.Er-2,0,32,106.5)),void 0!==t._r&&void 0!==t.gr&&(e.fillStyle="rgba(255, 0, 0,)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART( 0.5)",e.fillRect(R+32*t.gr.Er-2,R+32*t._r.Ar-2,32,32)),e.textAlign="left",e.textBaseline="middle",e.fillStyle="black",e.fillText("W=SWAP",R+32*y.length,R),e.fillText("F=C_XYZ",R+32*y.length,30.5),e.fillText("P=POLYGON",R+32*y.length,50.5),e.fillText("space=unmark",R+32*y.length,70.5),e.fillText("I=ISWAP",R+32*y.length,90.5),e.fillText("L=TIMELINEFOCUS",R+32*y.length,110.5)});{var _t=m.rev;const p=new ft;t=()=>{p.yr();try{var t,r=(()=>{var t=document.location.hash.substring(1),r=new Map;if(""!==t)for(var e of t.split("&")){var i,o=e.indexOf("=");-1!==o&&(i=e.substring(0,o),e=decodeURIComponent(e.substring(o+1)),r.set(i,e))}return r})(),e=(r.has("circuit")||("[[[DEFAULT-CIRCUIT-CONTENT-LITERAL]]]"===(t=document.getElementById("txtDefaultCircuit")).value.replaceAll("_","-")?r.set("circuit",""):r.set("circuit",t.value)),p.Ir(r.get("circuit")),u.D(r.get("circuit"))),i=e.B();_t.clear(i),e.P.every(t=>t.O())&&1===r.size&&i===r.get("circuit")?p.mr():p.pr(i,ct(i))}catch(t){throw new Error(t)}},window.addEventListener()CRUMBLE_PART");
    result.append(R"CRUMBLE_PART("popstate",t),t(),_t.Qt().gt()._t(1).subscribe(t=>{p.pr(t,ct(t))})}m.Tr.Tt().subscribe(t=>requestAnimationFrame(()=>it(m.canvas.getContext("2d"),t))),window.addEventListener("focus",()=>{m.Or.ht()}),window.addEventListener("blur",()=>{m.Or.ht()});
)CRUMBLE_PART");
    result.append(R"CRUMBLE_PART(</script>
)CRUMBLE_PART");
    return result;
}
