name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  upload_dev_release_to_pypi:
#    needs: run_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: echo TEST
#    - uses: actions/download-artifact@v2
#      with:
#        name: artifact
#        path: dist
#    - uses: pypa/gh-action-pypi-publish@v1.4.2
#      with:
#        user: __token__
#        password: ${{ secrets.pypi_password }}
